name: json-yaml-validate 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull requests

jobs:
  json-yaml-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          comment: "true" # enable comment mode
          yaml_exclude_regex: "(charts/external-dns/templates.*|mkdocs.yml)"
